FROM continuumio/miniconda3

WORKDIR /app

ENV PATH /opt/conda/bin:$PATH

RUN apt-get update && apt-get install -yq curl wget jq vim

# Copy environment YAML file
COPY environment.yml /app/environment.yml

# Install dependencies in a Conda environment (e.g., named "myenv")
RUN conda env create -f /app/environment.yml

# Configure the shell to use Conda by default for any shell commands
SHELL ["conda", "run", "-n", "python_env", "/bin/bash", "-c"]

# Install any needed packages
RUN pip install git+https://github.com/bp-kelley/descriptastorus "flaml[automl]"

# Copy the rest of your application code
COPY . /app

RUN pip install flask flask_cors openAI

# Expose port (Heroku expects the app to bind to $PORT)
EXPOSE 9999

# Use `conda run` to launch your app in the Conda environment
#CMD [ "/bin/bash", "-c", "source activate python_env && nohup jupyter lab --ip=0.0.0.0 --port=9999 --no-browser --allow-root --NotebookApp.token='' > jupyter.log 2>&1 & bash" ]
CMD [ "/bin/bash", "-c", "source activate python_env &&  python app.py && bash" ]

# Run app.py when the container launches
CMD ["python", "app.py"]
